[package]
name = "pengu/testplace"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
Promise = "evaera/promise@4.0.0"
FastSignal = "lucasmzreal/fastsignal@10.3.2"
Squash = "data-oriented-house/squash@2.5.0"
Vide = "centau/vide@0.3.1"
Classpp = "tenebrisnoctua/classpp@1.2.1"